arch:
- aarch64
- amd64
- armv7
- armhf
description: Promtail for Home Assistant
image: ghcr.io/tiagoasousa/promtail
init: false
journald: true
map:
- config
- share
- ssl
name: Promtail
options:
  client:
    url: https://loki.tsousa.xyz/loki/api/v1/push
  log_level: info
ports:
  9080/tcp: null
ports_description:
  9080/tcp: Promtail web server
schema:
  additional_pipeline_stages: str?
  additional_scrape_configs: str?
  client:
    cafile: str?
    certfile: str?
    keyfile: str?
    password: password?
    servername: str?
    url: str
    username: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  skip_default_scrape_config: bool?
slug: promtail
url: https://github.com/tiagoasousa/addon-promtail
version: latest
watchdog: http://[HOST]:[PORT:9080]/ready
